version: '3'
services:
  ehrmantraut:
    build: ./ehrmantraut
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - DATALAKE
    ports:
      - "5000:5000"
    volumes:
      - ./state/ehrmantraut:/usr/src/app/mlflow
