Parameters:
  ProjectName:
    Type: String
    Description: Name of the project this resources belongs to
  GroupName:
    Type: String
    Description: Name of Group
  OrgName:
    Type: String
    Description: Name of the organization

Resources:
  BaseUserGroup:
    Type: AWS::IAM::Group
    DeletionPolicy: Delete
    Properties:
      GroupName: !Ref GroupName
      Path: !Sub "/${OrgName}/"
  BaseUserManageMFAPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: "BaseUserManageMFA"
      Groups:
        - !Ref BaseUserGroup
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - "iam:ListVirtualMFADevices"
            Resource:
              - "*"
          - Effect: Allow
            Action:
              - "iam:ListMFADevices"
            Resource:
              - "arn:aws:iam::*:mfa/*"
              - "arn:aws:iam::*:user/${aws:username}"
              - !Sub "arn:aws:iam::*:user/${OrgName}/${!aws:username}"
          - Effect: Allow
            Action:
              - "iam:CreateVirtualMFADevice"
              - "iam:DeleteVirtualMFADevice"
              - "iam:EnableMFADevice"
              - "iam:ResyncMFADevice"
            Resource:
              - "arn:aws:iam::*:mfa/${aws:username}"
              - "arn:aws:iam::*:user/${aws:username}"
              - !Sub "arn:aws:iam::*:user/${OrgName}/${!aws:username}"
          - Effect: Allow
            Action:
              - "iam:DeactivateMFADevice"
            Resource:
              - "arn:aws:iam::*:mfa/${aws:username}"
              - "arn:aws:iam::*:user/${aws:username}"
              - !Sub "arn:aws:iam::*:user/${OrgName}/${!aws:username}"
            Condition:
              Bool:
                aws:MultiFactorAuthPresent: "true"
              NumericLessThanEquals:
                aws:MultiFactorAuthAge: 43200
  BaseUserManageAccessKeysPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: "BaseUserManageAccessKeys"
      Groups:
        - !Ref BaseUserGroup
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
                - "iam:CreateAccessKey"
                - "iam:DeleteAccessKey"
                - "iam:ListAccessKeys"
                - "iam:UpdateAccessKey"
                - "iam:GetAccessKeyLastUsed"
            Resource:
              - !Sub "arn:aws:iam::${AWS::AccountId}:user/${!aws:username}"
              - !Sub "arn:aws:iam::${AWS::AccountId}:user/${OrgName}/${!aws:username}"
            Condition:
              Bool:
                aws:MultiFactorAuthPresent: "true"
              NumericLessThanEquals:
                aws:MultiFactorAuthAge: 43200
  BaseUserListIAMUsersPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: "BaseUserListIAMUsers"
      Groups:
        - !Ref BaseUserGroup
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - "iam:GetAccountSummary"
              - "iam:ListAccountAliases"
              - "iam:ListGroupsForUser"
            Resource:
              - !Sub "arn:aws:iam::${AWS::AccountId}:user/*"
            Condition:
              Bool:
                aws:MultiFactorAuthPresent: "true"
              NumericLessThanEquals:
                aws:MultiFactorAuthAge: 43200
          - Effect: Allow
            Action:
              - "iam:ListUsers"
            Resource:
              - "*"
          - Effect: Allow
            Action:
              - "iam:GetUser"
            Resource:
              - !Sub "arn:aws:iam::${AWS::AccountId}:user/${!aws:username}"
              - !Sub "arn:aws:iam::${AWS::AccountId}:user/${OrgName}/${!aws:username}"
  BaseUserUpdateIAMPasswordPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: "BaseUsersUpdatePassword"
      Groups:
        - !Ref BaseUserGroup
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - "iam:GetAccountPasswordPolicy"
            Resource:
              - "*"
          - Effect: Allow
            Action:
              - "iam:ChangePassword"
              - "iam:GetLoginProfile"
              - "iam:UpdateLoginProfile"
            Resource:
              - !Sub "arn:aws:iam::${AWS::AccountId}:user/${!aws:username}"
              - !Sub "arn:aws:iam::${AWS::AccountId}:user/${OrgName}/${!aws:username}"